/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog/ConfirmDialog.vue')['default']
    MonthSelect: typeof import('./src/components/MonthSelect/MonthSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    ToastMessage: typeof import('./src/components/ToastMessage/ToastMessage.vue')['default']
  }
}
