/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/channel/AddchannelDialog': RouteRecordInfo<'/channel/AddchannelDialog', '/channel/AddchannelDialog', Record<never, never>, Record<never, never>>,
    '/channel/Channel': RouteRecordInfo<'/channel/Channel', '/channel/Channel', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/layout/AppBar': RouteRecordInfo<'/layout/AppBar', '/layout/AppBar', Record<never, never>, Record<never, never>>,
    '/layout/Drawer': RouteRecordInfo<'/layout/Drawer', '/layout/Drawer', Record<never, never>, Record<never, never>>,
    '/layout/View': RouteRecordInfo<'/layout/View', '/layout/View', Record<never, never>, Record<never, never>>,
    '/log/Logs': RouteRecordInfo<'/log/Logs', '/log/Logs', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/overview/Overview': RouteRecordInfo<'/overview/Overview', '/overview/Overview', Record<never, never>, Record<never, never>>,
    '/setting/Settings': RouteRecordInfo<'/setting/Settings', '/setting/Settings', Record<never, never>, Record<never, never>>,
  }
}
