/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/apikeys/': RouteRecordInfo<'/apikeys/', '/apikeys', Record<never, never>, Record<never, never>>,
    '/apikeys/AddKeyDialog': RouteRecordInfo<'/apikeys/AddKeyDialog', '/apikeys/AddKeyDialog', Record<never, never>, Record<never, never>>,
    '/channel/': RouteRecordInfo<'/channel/', '/channel', Record<never, never>, Record<never, never>>,
    '/channel/AddchannelDialog': RouteRecordInfo<'/channel/AddchannelDialog', '/channel/AddchannelDialog', Record<never, never>, Record<never, never>>,
    '/channel/ChannelList': RouteRecordInfo<'/channel/ChannelList', '/channel/ChannelList', Record<never, never>, Record<never, never>>,
    '/chat/': RouteRecordInfo<'/chat/', '/chat', Record<never, never>, Record<never, never>>,
    '/chat/setting/Setting': RouteRecordInfo<'/chat/setting/Setting', '/chat/setting/Setting', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/knowledgeBase/': RouteRecordInfo<'/knowledgeBase/', '/knowledgeBase', Record<never, never>, Record<never, never>>,
    '/knowledgeBase/KnowledgeBaseFile': RouteRecordInfo<'/knowledgeBase/KnowledgeBaseFile', '/knowledgeBase/KnowledgeBaseFile', Record<never, never>, Record<never, never>>,
    '/layout/AppBar': RouteRecordInfo<'/layout/AppBar', '/layout/AppBar', Record<never, never>, Record<never, never>>,
    '/layout/Drawer': RouteRecordInfo<'/layout/Drawer', '/layout/Drawer', Record<never, never>, Record<never, never>>,
    '/layout/View': RouteRecordInfo<'/layout/View', '/layout/View', Record<never, never>, Record<never, never>>,
    '/log/': RouteRecordInfo<'/log/', '/log', Record<never, never>, Record<never, never>>,
    '/login/Login': RouteRecordInfo<'/login/Login', '/login/Login', Record<never, never>, Record<never, never>>,
    '/login/Logon': RouteRecordInfo<'/login/Logon', '/login/Logon', Record<never, never>, Record<never, never>>,
    '/login/Reset': RouteRecordInfo<'/login/Reset', '/login/Reset', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/model/': RouteRecordInfo<'/model/', '/model', Record<never, never>, Record<never, never>>,
    '/overview/': RouteRecordInfo<'/overview/', '/overview', Record<never, never>, Record<never, never>>,
    '/overview/ChannelStat': RouteRecordInfo<'/overview/ChannelStat', '/overview/ChannelStat', Record<never, never>, Record<never, never>>,
    '/overview/ModelUsageRatio': RouteRecordInfo<'/overview/ModelUsageRatio', '/overview/ModelUsageRatio', Record<never, never>, Record<never, never>>,
    '/overview/ModelUsageStats': RouteRecordInfo<'/overview/ModelUsageStats', '/overview/ModelUsageStats', Record<never, never>, Record<never, never>>,
    '/overview/RequestCount': RouteRecordInfo<'/overview/RequestCount', '/overview/RequestCount', Record<never, never>, Record<never, never>>,
    '/overview/Status': RouteRecordInfo<'/overview/Status', '/overview/Status', Record<never, never>, Record<never, never>>,
    '/overview/UserUsageRatio': RouteRecordInfo<'/overview/UserUsageRatio', '/overview/UserUsageRatio', Record<never, never>, Record<never, never>>,
    '/setting/': RouteRecordInfo<'/setting/', '/setting', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
  }
}
